---
apiVersion: batch/v1
kind: Job
metadata:  
  annotations:
    argocd.argoproj.io/hook: PreSync  
    argocd.argoproj.io/sync-wave: "0"
  generateName: upgrade-sql-schema-1
spec:
  template:
    spec:
      containers:
        - name: upgrade-sql-schema
          image: alpine:latest
          command: ["sleep", "5"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync  
    argocd.argoproj.io/sync-wave: "1"
  generateName: upgrade-sql-schema-2
spec:
  template:
    spec:
      containers:
        - name: upgrade-sql-schema
          image: alpine:latest
          command: ["sleep", "5"]
      restartPolicy: Never

